version: '2'

services:
  # mysql:
  #   image: 'mysql:5.7.20'
  #   env_file:
  #     - '.env'
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   ports:
  #     - '3306:3306'

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - ./redis:/var/lib/redis
    ports:
      - '6379:6379'

  website:
    build: .
    command: >
      gunicorn -b :8000
        --access-logfile -
        --access-logformat '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s" in %(D)sµs'
        --reload
        "app.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/app'
    ports:
      - '8000:8000'

  celery:
    build: .
    command: celery worker -l info -A app.blueprints.contact.tasks
    env_file:
      - '.env'
    volumes:
      - '.:/app'
