version: '3'
services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    volumes:
      - ~/Documents/adv_portfolio/docker_blueprint:/app
    links:
      - db:mongodb
    container_name: blueprint_web_1
    depends_on:
      - db
  db:
    image: mongo:3.0.2
    container_name: blueprint_db_1

