web:
  build: ./web
  command: python -u ./app.py
  ports:
    - "5000:5000"
  volumes:
    # name volume anything you like
    - ~/Documents/adv_portfolio/flask_app_starter:/flask_app
  links:
    - db
db:
  image: mongo:3.0.2
